document.addEventListener("DOMContentLoaded", () => {
  const products = [
    {
      src: "73.png",
      name: "Biba",
      cata: "Cotton Kurta",
      oldPrice: "Rs.1899",
      price: "Rs.1425",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "74.png",
      name: "W for Woman",
      cata: "Anarkali Kurta",
      oldPrice: "Rs.2299",
      price: "Rs.1725",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "75.png",
      name: "Libas",
      cata: "Straight Kurta",
      oldPrice: "Rs.1699",
      price: "Rs.1275",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "76.png",
      name: "Aurelia",
      cata: "Printed Kurta",
      oldPrice: "Rs.1499",
      price: "Rs.1125",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "77.png",
      name: "Indya",
      cata: "Festive Kurta",
      oldPrice: "Rs.2899",
      price: "Rs.2175",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "78.png",
      name: "Rain & Rainbow",
      cata: "Flared Kurta",
      oldPrice: "Rs.1999",
      price: "Rs.1499",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "79.png",
      name: "Global Desi",
      cata: "Designer Kurta",
      oldPrice: "Rs.2599",
      price: "Rs.1949",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "80.png",
      name: "Soch",
      cata: "Embroidered Kurta",
      oldPrice: "Rs.2799",
      price: "Rs.2099",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "81.png",
      name: "Jaipur Kurti",
      cata: "Straight Kurta",
      oldPrice: "Rs.1399",
      price: "Rs.1049",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "82.png",
      name: "Vishudh",
      cata: "Casual Kurta",
      oldPrice: "Rs.1199",
      price: "Rs.899",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "83.png",
      name: "Varanga",
      cata: "Rayon Kurta",
      oldPrice: "Rs.1499",
      price: "Rs.1125",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "84.png",
      name: "Gulmohar Jaipur",
      cata: "Ethnic Kurta",
      oldPrice: "Rs.2199",
      price: "Rs.1649",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "85.png",
      name: "Anouk",
      cata: "Mandarin Collar Kurta",
      oldPrice: "Rs.1799",
      price: "Rs.1349",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "86.png",
      name: "Tokyo Talkies",
      cata: "Cotton Blend Kurta",
      oldPrice: "Rs.1299",
      price: "Rs.975",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "87.png",
      name: "Sangria",
      cata: "Office Wear Kurta",
      oldPrice: "Rs.1599",
      price: "Rs.1199",
      OFF: "(25%)",
      type: "womenKurtas",
    },
    {
      src: "88.png",
      name: "House of Pataudi",
      cata: "Occasion Kurta",
      oldPrice: "Rs.2999",
      price: "Rs.2249",
      OFF: "(25%)",
      type: "womenKurtas",
    },

    {
      src: "1.png",
      name: "The Indian Garage Co",
      cata: "Regular Fit Casual shirt",
      oldPrice: "Rs.999",
      price: "Rs.539",
      OFF: "(46%)",
      type: "shirt",
    },
    {
      src: "2.png",
      name: "Roadster",
      cata: "Cotton Casual Shirt",
      oldPrice: "Rs.2999",
      price: "Rs.1888",
      OFF: "(40%)",
      type: "shirt",
    },
    {
      src: "3.png",
      name: "Tommy Hilfiger",
      cata: "Men Solid Cotton Shirt",
      oldPrice: "Rs.4699",
      price: "Rs.3399",
      OFF: "(32%)",
      type: "shirt",
    },
    {
      src: "4.png",
      name: "Tommy Hilfiger",
      cata: "Slim Fit Opaque Casual Shirt",
      oldPrice: "Rs.4099",
      price: "Rs.3299",
      OFF: "(30%)",
      type: "shirt",
    },
    {
      src: "5.png",
      name: "Mast & Harbour",
      cata: "Stripped Casual Shirt",
      oldPrice: "Rs.5999",
      price: "Rs.4999",
      OFF: "(50%)",
      type: "shirt",
    },
    {
      src: "6.png",
      name: "Roadster",
      cata: "Pure Cotton Casual Shirt",
      oldPrice: "Rs.999",
      price: "Rs.659",
      OFF: "(67%)",
      type: "shirt",
    },
    {
      src: "7.png",
      name: "Puma",
      cata: "Slim Fit Opaque Casual Shirt",
      oldPrice: "Rs.4999",
      price: "Rs.4000",
      OFF: "(45%)",
      type: "shirt",
    },
    {
      src: "8.png",
      name: "HRX",
      cata: "Men Printed T-Shirt",
      oldPrice: "Rs.999",
      price: "Rs.459",
      OFF: "(55%)",
      type: "shirt",
    },
    {
      src: "9.png",
      name: "Bewakoof",
      cata: "Graphic T-Shirt",
      oldPrice: "Rs.1099",
      price: "Rs.599",
      OFF: "(35%)",
      type: "shirt",
    },
    {
      src: "10.png",
      name: "Puma",
      cata: "Sporty Dry Fit T-Shirt",
      oldPrice: "Rs.1499",
      price: "Rs.789",
      OFF: "(40%)",
      type: "shirt",
    },
    {
      src: "11.png",
      name: "Puma",
      cata: "Slim Fit Opaque Casual Shirt",
      oldPrice: "Rs.5999",
      price: "Rs.4000",
      OFF: "(45%)",
      type: "shirt",
    },
    {
      src: "12.png",
      name: "HRX",
      cata: "Men Printed T-Shirt",
      price: "Rs.459",
      oldPrice: "Rs.999",
      OFF: "(55%)",
      type: "shirt",
    },

    {
      src: "13.png",
      name: "Levi's",
      cata: "Graphic",
      oldPrice: "Rs.1599",
      price: "Rs.999",
      OFF: "(38%)",
      type: "tshirt",
    },
    {
      src: "14.png",
      name: "U.S. Polo Assn.",
      cata: "Polo",
      oldPrice: "Rs.1999",
      price: "Rs.1299",
      OFF: "(35%)",
      type: "tshirt",
    },
    {
      src: "15.png",
      name: "Jack & Jones",
      cata: "Printed",
      oldPrice: "Rs.1299",
      price: "Rs.779",
      OFF: "(40%)",
      type: "tshirt",
    },
    {
      src: "16.png",
      name: "H&M",
      cata: "Casual",
      oldPrice: "Rs.799",
      price: "Rs.499",
      OFF: "(38%)",
      type: "tshirt",
    },
    {
      src: "17.png",
      name: "Zara",
      cata: "Plain",
      oldPrice: "Rs.1799",
      price: "Rs.1299",
      OFF: "(28%)",
      type: "tshirt",
    },
    {
      src: "18.png",
      name: "Nike",
      cata: "Sports",
      oldPrice: "Rs.2195",
      price: "Rs.1499",
      OFF: "(31%)",
      type: "tshirt",
    },
    {
      src: "19.png",
      name: "Adidas",
      cata: "Activewear",
      oldPrice: "Rs.1999",
      price: "Rs.1199",
      OFF: "(40%)",
      type: "tshirt",
    },
    {
      src: "20.png",
      name: "Reebok",
      cata: "Dry Fit",
      oldPrice: "Rs.1299",
      price: "Rs.779",
      OFF: "(40%)",
      type: "tshirt",
    },
    {
      src: "21.png",
      name: "HRX",
      cata: "Crew Neck",
      oldPrice: "Rs.999",
      price: "Rs.459",
      OFF: "(54%)",
      type: "tshirt",
    },
    {
      src: "22.png",
      name: "Bewakoof",
      cata: "Oversized",
      oldPrice: "Rs.1199",
      price: "Rs.699",
      OFF: "(42%)",
      type: "tshirt",
    },
    {
      src: "23.png",
      name: "Superdry",
      cata: "Logo Print",
      oldPrice: "Rs.3499",
      price: "Rs.2599",
      OFF: "(25%)",
      type: "tshirt",
    },
    {
      src: "24.png",
      name: "Tommy Hilfiger",
      cata: "Classic",
      oldPrice: "Rs.2499",
      price: "Rs.1749",
      OFF: "(30%)",
      type: "tshirt",
    },

    {
      src: "25.png",
      name: "Levi's",
      cata: "Slim Fit",
      oldPrice: "Rs.3299",
      price: "Rs.2399",
      OFF: "(27%)",
      type: "jeans",
    },
    {
      src: "26.png",
      name: "Pepe Jeans",
      cata: "Tapered",
      oldPrice: "Rs.2999",
      price: "Rs.1999",
      OFF: "(33%)",
      type: "jeans",
    },
    {
      src: "27.png",
      name: "Wrangler",
      cata: "Regular Fit",
      oldPrice: "Rs.2499",
      price: "Rs.1699",
      OFF: "(32%)",
      type: "jeans",
    },
    {
      src: "28.png",
      name: "Jack & Jones",
      cata: "Skinny Fit",
      oldPrice: "Rs.3499",
      price: "Rs.2449",
      OFF: "(30%)",
      type: "jeans",
    },
    {
      src: "29.png",
      name: "Lee",
      cata: "Straight Fit",
      oldPrice: "Rs.2799",
      price: "Rs.1899",
      OFF: "(32%)",
      type: "jeans",
    },
    {
      src: "30.png",
      name: "Spykar",
      cata: "Distressed",
      oldPrice: "Rs.3199",
      price: "Rs.2149",
      OFF: "(33%)",
      type: "jeans",
    },
    {
      src: "31.png",
      name: "Mufti",
      cata: "Narrow Fit",
      oldPrice: "Rs.2699",
      price: "Rs.1799",
      OFF: "(33%)",
      type: "jeans",
    },
    {
      src: "32.png",
      name: "Flying Machine",
      cata: "Washed",
      oldPrice: "Rs.2299",
      price: "Rs.1599",
      OFF: "(30%)",
      type: "jeans",
    },
    {
      src: "33.png",
      name: "U.S. Polo Assn.",
      cata: "Slim Tapered",
      oldPrice: "Rs.2999",
      price: "Rs.2199",
      OFF: "(27%)",
      type: "jeans",
    },
    {
      src: "34.png",
      name: "H&M",
      cata: "Relaxed Fit",
      oldPrice: "Rs.2499",
      price: "Rs.1699",
      OFF: "(32%)",
      type: "jeans",
    },
    {
      src: "35.png",
      name: "Zara",
      cata: "Carrot Fit",
      oldPrice: "Rs.3599",
      price: "Rs.2699",
      OFF: "(25%)",
      type: "jeans",
    },
    {
      src: "36.png",
      name: "Denizen",
      cata: "Stretchable",
      oldPrice: "Rs.1999",
      price: "Rs.1399",
      OFF: "(30%)",
      type: "jeans",
    },

    {
      src: "37.png",
      name: "Park Avenue",
      cata: "Eau de Parfum",
      oldPrice: "Rs.799",
      price: "Rs.499",
      OFF: "(38%)",
      type: "perfume",
    },
    {
      src: "38.png",
      name: "FOGG",
      cata: "Body Spray",
      oldPrice: "Rs.299",
      price: "Rs.199",
      OFF: "(33%)",
      type: "perfume",
    },
    {
      src: "39.png",
      name: "Denver",
      cata: "Deodorant",
      oldPrice: "Rs.250",
      price: "Rs.179",
      OFF: "(28%)",
      type: "perfume",
    },
    {
      src: "40.png",
      name: "Skinn by Titan",
      cata: "Eau de Parfum",
      oldPrice: "Rs.1999",
      price: "Rs.1499",
      OFF: "(25%)",
      type: "perfume",
    },
    {
      src: "41.png",
      name: "Wild Stone",
      cata: "Body Spray",
      oldPrice: "Rs.275",
      price: "Rs.199",
      OFF: "(28%)",
      type: "perfume",
    },
    {
      src: "42.png",
      name: "Bella Vita",
      cata: "Luxury Scent",
      oldPrice: "Rs.899",
      price: "Rs.649",
      OFF: "(28%)",
      type: "perfume",
    },
    {
      src: "43.png",
      name: "Ajmal",
      cata: "Attar",
      oldPrice: "Rs.999",
      price: "Rs.749",
      OFF: "(25%)",
      type: "perfume",
    },
    {
      src: "44.png",
      name: "Zara",
      cata: "Eau de Toilette",
      oldPrice: "Rs.1590",
      price: "Rs.1190",
      OFF: "(25%)",
      type: "perfume",
    },
    {
      src: "45.png",
      name: "Engage",
      cata: "Deodorant",
      oldPrice: "Rs.250",
      price: "Rs.169",
      OFF: "(32%)",
      type: "perfume",
    },
    {
      src: "46.png",
      name: "The Man Company",
      cata: "Body Mist",
      oldPrice: "Rs.799",
      price: "Rs.599",
      OFF: "(25%)",
      type: "perfume",
    },
    {
      src: "47.png",
      name: "Beardo",
      cata: "Eau de Parfum",
      oldPrice: "Rs.1200",
      price: "Rs.899",
      OFF: "(25%)",
      type: "perfume",
    },
    {
      src: "48.png",
      name: "Villain",
      cata: "Luxury Spray",
      oldPrice: "Rs.999",
      price: "Rs.699",
      OFF: "(30%)",
      type: "perfume",
    },

    {
      src: "49.png",
      name: "Nike Air Max",
      cata: "Running Shoes",
      oldPrice: "Rs.5999",
      price: "Rs.4499",
      OFF: "(25%)",
      type: "shoes",
    },
    {
      src: "50.png",
      name: "Adidas Ultraboost",
      cata: "Sports Shoes",
      oldPrice: "Rs.7999",
      price: "Rs.5999",
      OFF: "(25%)",
      type: "shoes",
    },
    {
      src: "51.png",
      name: "Puma Smash",
      cata: "Casual Shoes",
      oldPrice: "Rs.3499",
      price: "Rs.2699",
      OFF: "(23%)",
      type: "shoes",
    },
    {
      src: "52.png",
      name: "Reebok Flexagon",
      cata: "Training Shoes",
      oldPrice: "Rs.3999",
      price: "Rs.2999",
      OFF: "(25%)",
      type: "shoes",
    },
    {
      src: "53.png",
      name: "Campus Maxico",
      cata: "Walking Shoes",
      oldPrice: "Rs.1999",
      price: "Rs.1499",
      OFF: "(25%)",
      type: "shoes",
    },
    {
      src: "54.png",
      name: "Bata Power",
      cata: "Formal Shoes",
      oldPrice: "Rs.2599",
      price: "Rs.1999",
      OFF: "(23%)",
      type: "shoes",
    },
    {
      src: "55.png",
      name: "Red Tape",
      cata: "Leather Shoes",
      oldPrice: "Rs.4999",
      price: "Rs.3749",
      OFF: "(25%)",
      type: "shoes",
    },
    {
      src: "56.png",
      name: "Woodland",
      cata: "Outdoor Shoes",
      oldPrice: "Rs.5999",
      price: "Rs.4599",
      OFF: "(23%)",
      type: "shoes",
    },
    {
      src: "57.png",
      name: "Sparx",
      cata: "Loafers",
      oldPrice: "Rs.2199",
      price: "Rs.1599",
      OFF: "(27%)",
      type: "shoes",
    },
    {
      src: "58.png",
      name: "Levi's",
      cata: "Sneakers",
      oldPrice: "Rs.2999",
      price: "Rs.2249",
      OFF: "(25%)",
      type: "shoes",
    },
    {
      src: "59.png",
      name: "HRX by Hrithik",
      cata: "Running Shoes",
      oldPrice: "Rs.3499",
      price: "Rs.2625",
      OFF: "(25%)",
      type: "shoes",
    },
    {
      src: "60.png",
      name: "Liberty",
      cata: "Formal Shoes",
      oldPrice: "Rs.3299",
      price: "Rs.2499",
      OFF: "(24%)",
      type: "shoes",
    },

    {
      src: "61.png",
      name: "Manyavar",
      cata: "Silk Kurta",
      oldPrice: "Rs.2999",
      price: "Rs.2249",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "62.png",
      name: "Fabindia",
      cata: "Cotton Kurta",
      oldPrice: "Rs.1999",
      price: "Rs.1499",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "63.png",
      name: "Sojanya",
      cata: "Printed Kurta",
      oldPrice: "Rs.1599",
      price: "Rs.1199",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "64.png",
      name: "W for Woman",
      cata: "Straight Kurta",
      oldPrice: "Rs.1799",
      price: "Rs.1349",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "65.png",
      name: "Biba",
      cata: "Flared Kurta",
      oldPrice: "Rs.2499",
      price: "Rs.1899",
      OFF: "(24%)",
      type: "kurta",
    },
    {
      src: "66.png",
      name: "Indo Era",
      cata: "Embroidered Kurta",
      oldPrice: "Rs.2199",
      price: "Rs.1649",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "67.png",
      name: "Libas",
      cata: "Anarkali Kurta",
      oldPrice: "Rs.2699",
      price: "Rs.1999",
      OFF: "(26%)",
      type: "kurta",
    },
    {
      src: "68.png",
      name: "Jompers",
      cata: "Casual Kurta",
      oldPrice: "Rs.1399",
      price: "Rs.1049",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "69.png",
      name: "Kisah",
      cata: "Festive Kurta",
      oldPrice: "Rs.3199",
      price: "Rs.2399",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "70.png",
      name: "Kurtawala",
      cata: "Linen Kurta",
      oldPrice: "Rs.1899",
      price: "Rs.1425",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "71.png",
      name: "House of Pataudi",
      cata: "Designer Kurta",
      oldPrice: "Rs.3499",
      price: "Rs.2625",
      OFF: "(25%)",
      type: "kurta",
    },
    {
      src: "72.png",
      name: "Aurelia",
      cata: "Office Wear Kurta",
      oldPrice: "Rs.1699",
      price: "Rs.1275",
      OFF: "(25%)",
      type: "kurta",
    },
  ];

  const grid = document.getElementById("shirtProductGrid");

  const allBtn = document.getElementById("showAllBtn");
  const shirtBtn = document.getElementById("showShirtsBtn");
  const tshirtBtn = document.getElementById("showTShirtsBtn");
  const jeansBtn = document.getElementById("showJeansBtn");
  const perfumeBtn = document.getElementById("showPerfumeBtn");
  const shoesBtn = document.getElementById("showShoesBtn");
  const kurtasBtn = document.getElementById("showKurtasBtn");
  const womenKurtas = document.getElementById("womenKurtasBtn");
  const searchInput = document.getElementById("searchInput");

  searchInput.addEventListener("input", () => {
    const searchTerm = searchInput.value.toLowerCase();

    const filteredProducts = products.filter((product) => {
      return (
        product.name.toLowerCase().includes(searchTerm) ||
        product.cata.toLowerCase().includes(searchTerm) ||
        product.type.toLowerCase().includes(searchTerm)
      );
    });
    renderProducts(filteredProducts);
  });

  function renderProducts(data) {
    grid.innerHTML = data
      .map(
        (item) => `
      <div class="bg-white p-3 shadow rounded">
        <img src="${item.src}" class="w-full h-48 object-cover object-top mb-2" alt="${item.name}">
        <div class="font-semibold text-gray-800">${item.name}</div>
        <div class="text-sm text-gray-500">${item.cata}</div>
        <div class="text-sm mt-1 flex items-center gap-2">
          <span class="line-through text-red-400">${item.oldPrice}</span>
          <span class="font-bold text-black">${item.price}</span>
          <span class="text-green-600">${item.OFF}</span>
        </div>
      </div>
    `
      )
      .join("");
  }

  function renderByType(type) {
    const filtered = products.filter((p) => p.type === type);
    renderProducts(filtered);
  }

  allBtn.addEventListener("click", () => renderProducts(products));
  shirtBtn.addEventListener("click", () => renderByType("shirt"));
  tshirtBtn.addEventListener("click", () => renderByType("tshirt"));
  jeansBtn.addEventListener("click", () => renderByType("jeans"));
  perfumeBtn.addEventListener("click", () => renderByType("perfume"));
  shoesBtn.addEventListener("click", () => renderByType("shoes"));
  kurtasBtn.addEventListener("click", () => renderByType("kurta"));
  womenKurtas.addEventListener("click", () => renderByType("womenKurtas"));

  renderProducts(products);
});
